version : '3.8'

services :
  nginx :
    container_name : nginx
    build : requirements/nginx
    ports :
      - "443:443"
    networks :
      - inception_net
    restart : always

    mariadb :
      container_name : mariadb
      build : requirements/mariadb
      ports :
        - "3306:3306"
      network :
          - inception_net
      restart : always

networks :
  inception_net :
    driver : bridge
